### ISSUE TITLE
Fail to install in proxy environment

### ISSUE THREAD

**Issue by devmiyax** [markushedvall/node-plantuml#28]
Under windows fail to install, if you are in proxy environment.
```
c:\> npm install node-plantuml

> node-plantuml@0.8.1 postinstall XXXXXXXXXXXXXXXXXXXXX
> node scripts/get-vizjs.js

events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: spawn java ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:247:19)
    at onErrorNT (internal/child_process.js:431:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:871:11)
    at internal/main/run_main_module.js:21:11
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:253:12)
    at onErrorNT (internal/child_process.js:431:16)
    [... lines matching original stack trace ...]
    at internal/main/run_main_module.js:21:11
```

**Comment by nmarijane** [comment]
Can you please just check if you have jre/jdk installed on ?

**Comment by markushedvall** [comment]
This error indicate that java is not available, or maybe need to be added to PATH?

During install java is needed to run testdot in Plantuml to check the ghraphviz installation. Maybe a pure js version of testdot could be implemented instead. However, without java the package wouldn't be usable anyway.
